export { About } from './About'
export { Build } from './Build'
export { Develop } from './Develop'
export { Hero } from './Hero'
export { Testimonials } from './Testimonials'
export { Update } from './Update'
